import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header/Header";
// import Footer from "./Components/Footer/Footer";

const GilroyRegular = localFont({
  src: "./fonts/Gilroy-Regular.ttf",
  variable: "--font-gilroy-regular",
  weight: "100",
});

const GilroyBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  variable: "--font-gilroy-bold",
  weight: "300",
});

const GilroySemibold = localFont({
  src: "./fonts/Gilroy-Semibold.ttf",
  variable: "--font-gilroy-semibold",
  weight: "600",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GilroyRegular.variable} ${GilroyBold.variable} ${GilroySemibold.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
